config/routes.rb
Rails.application.routes.draw do
  resources :follows
  resources :categories do
    resources :posts
  end

  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users

  resources :users
  post 'users/:id/follow', to: "users#follow", as: "follow_user"
	post 'users/:id/unfollow', to: "users#unfollow", as: "unfollow_user"

  resources :subscribers
  get 'about/index'
  get 'promo/index'

  resources :posts do
    resources :comments
    resources :favorites
  end

  get 'users', to: 'users#index'
  get 'users/:id' => 'users#show'
  delete 'users/:id', to: 'users#destroy'

  get 'users/:id/following', :to => "users#following", :as => :following

  get 'posts/index'

  get 'promo', to: 'promo#index'
  get 'about', to: 'about#index'
  get 'restaurants', to: 'restaurants#index'
  get 'cafes', to: 'cafes#index'
  get 'bars', to: 'bars#index'
  get 'dishes', to: 'dishes#index'



  root 'posts#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/follow.rb
class Follow < ApplicationRecord
  belongs_to :follower, class_name: 'User'
  belongs_to :followee, class_name: 'User'
end

app/models/post.rb
class Post < ApplicationRecord
	  # scope :filter_by_starts_with, -> (content) { where("content like ?", "%#{content}%")}
		scope :filter_by_starts_with, -> (search) { where("name like :search or title like :search or content like :search", search: "%#{search}%")}
	  scope :filter_by_user, -> (user) { where user: user }
	  scope :filter_by_category, -> (category) { where category: category }
		validates :name, :presence => true
		validates :title, :presence => true,
											:length => { :minimum => 5 }
    mount_uploader :image, ImageUploader
    has_many :comments, :dependent => :destroy
		has_many :favorites, dependent: :destroy
			belongs_to :user
			belongs_to :category

end

app/models/subscriber.rb
class Subscriber < ApplicationRecord
  validates :email, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :favorites, dependent: :destroy
  has_many :favorited_posts, :through => :favorites, :source => :post
  has_many :followed_users, foreign_key: :follower_id, class_name: 'Follow'
  has_many :followees, through: :followed_users
  has_many :following_users, foreign_key: :followee_id, class_name: 'Follow'
  has_many :followers, through: :following_users
  has_many :comments, dependent: :destroy
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/cafes_controller.rb
class CafesController < ApplicationController
      before_action :authenticate_user!, except: [:index, :show]
      before_action :set_post, only: %i[ show edit update destroy ]

      # GET /posts or /posts.json
      def index
        @posts = Post.where(category_id: 2)
      end
        # if params.has_key?(:category)
        #   @category = Category.find_by_name(params[:category])
        #   @posts = Post.where(category: @category)
        # else
        #   @posts = Post.all
        # end


      # GET /posts/1 or /posts/1.json
      def show
      end

      # GET /posts/new
      def new
        @post = Post.new
      end

      # GET /posts/1/edit
      def edit
      end

      # POST /posts or /posts.json
      def create
        @post = Post.new(post_params.merge(user_id: current_user.id))

        respond_to do |format|
          if @post.save
            format.html { redirect_to @post, notice: "Post was successfully created." }
            format.json { render :show, status: :created, location: @post }
          else
            format.html { render :new, status: :unprocessable_entity }
            format.json { render json: @post.errors, status: :unprocessable_entity }
          end
        end
      end

      # PATCH/PUT /posts/1 or /posts/1.json
      def update
        respond_to do |format|
          if @post.update(post_params)
            format.html { redirect_to @post, notice: "Ура" }
            format.json { render :show, status: :ok, location: @post }
          else
            format.html { render :edit, status: :unprocessable_entity }
            format.json { render json: @post.errors, status: :unprocessable_entity }
          end
        end
      end

      # DELETE /posts/1 or /posts/1.json
      def destroy
        @post.destroy
        respond_to do |format|
          format.html { redirect_to posts_url, notice: "Увы" }
          format.json { head :no_content }
        end
      end

      private
      def filtering_params(params)
        params.slice(:user, :category, :starts_with)
      end
        # Use callbacks to share common setup or constraints between actions.
        def set_post
          @post = Post.find(params[:id])
        end

        # Only allow a list of trusted parameters through.
        def post_params
          params.require(:post).permit(:name, :title, :content, :image, :category_id)
        end

    end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
    render component: 'Users', props: { users: @users }
    respond_to do |format|
      format.html  # index.html.erb
      format.json  { render :json => @users }
    end

  end

   # class UsersController < ApplicationController
#   def index
#     @users = User.all
#   end

  def show
    @user = User.find(params[:id])
    if @user
      @posts = @user.favorited_posts
      render actions: :show
      @favorites = @user.favorites.all
    else
        render file: 'public/404', status: 404, formats: [:html]
    end
  end

def favorited?(post)
    favorites.find_by(post_id: post.id).present?
  end

  def follow
  @user = User.find(params[:id])
  current_user.followees << @user
  redirect_back(fallback_location: user_path(@user))
end

def unfollow
  @user = User.find(params[:id])
  current_user.followed_users.find_by(followee_id: @user.id).destroy
  redirect_back(fallback_location: user_path(@user))
end

def following
  @user = User.find(params[:id])
  if @user
    @follow = @user.followed_users
    render actions: :show
    @following = @user.followees.all
  end
end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_path, notice: 'User deleted.'
  end

end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cafes_helper.rb
module CafesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/promo_helper.rb
module PromoHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/subscribers_helper.rb
module SubscribersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/following.html.erb
<% @follow.each do |follow| %>
  <br><%= link_to follow.followee_id, user_path(follow.followee_id)  %>
<% end %>

app/views/users/index.html.erb
<%= stylesheet_link_tag "users" %>


<div class="users_container">
  <h1>Люди</h1>
  <div class="button_newuser">
  <%= link_to 'Добавить автора', new_category_path %>
  </div>
  <div class="razdel"><p>Пользователи</p></div>


<table>
  <thead class="plashka">
    <tr>
      <th>ID</th>
      <th>Имя</th>
      <th>Почта</th>
      <th>Cтатус</th>
      <th></th>
      <th></th>

    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.id %></td>
        <td><%= user.username %></td>
        <td><%= link_to user.email, user %></td>
        <td><%= (user.isadmin) == true ? "Администратор" : "Пользователь" %></td>
        <td><%= link_to 'Открыть', user %></td>
        <td><%= link_to 'Удалить', user, method: :delete, data: { confirm: 'Вы уверены?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

</div>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<%= stylesheet_link_tag "users" %>


<div class="users_container">

  <% if user_signed_in? %>
   <div class="signout"><%= link_to 'Выйти', destroy_user_session_path, method: :delete %></div>
 <% else %>
   <%= link_to 'Войти', new_user_session_path %>  <%= link_to 'Зарегистрироваться', new_user_registration_path %>
 <% end %>

  <div class="userphoto"></div>
  <div class="usernamebox">
  <h2>Борис</h2>
  <a href="/users/edit"><div class="editicon"></div></a>
  </div>
  <% if user_signed_in? && current_user.isadmin == true %>
     <div class="admin"><%= (@user.isadmin) == true ? "(Администратор)" : "Пользователь" %></div>
  <% end %>
  <div class="addcollection"></div>
  <div class="collectionsrow1">
    <div class="collection1"></div>
    <div class="collection2"></div>
    <div class="collection3"></div>
    <div class="collection4"></div>
  </div>
  <div class="collectionsrow2">
    <div class="collection5"></div>
    <div class="collection6"></div>
    <div class="collection7"></div>
    <div class="collection8"></div>
  </div>


 </div>