config/routes.rb
Rails.application.routes.draw do
  resources :follows
  resources :categories do
    resources :posts
  end

  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users

  resources :users
  post 'users/:id/follow', to: "users#follow", as: "follow_user"
	post 'users/:id/unfollow', to: "users#unfollow", as: "unfollow_user"

  resources :subscribers
  get 'about/index'
  get 'promo/index'

  resources :posts do
    resources :comments
    resources :favorites
  end

  get 'users', to: 'users#index'
  get 'users/:id' => 'users#show'
  delete 'users/:id', to: 'users#destroy'

  get 'users/:id/following', :to => "users#following", :as => :following

  get 'posts/index'

  get 'promo', to: 'promo#index'
  get 'about', to: 'about#index'
  get 'restaurants', to: 'restaurants#index'
  get 'cafes', to: 'cafes#index'
  get 'bars', to: 'bars#index'
  get 'dishes', to: 'dishes#index'



  root 'posts#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/follow.rb
class Follow < ApplicationRecord
  belongs_to :follower, class_name: 'User'
  belongs_to :followee, class_name: 'User'
end

app/models/post.rb
class Post < ApplicationRecord
	  # scope :filter_by_starts_with, -> (content) { where("content like ?", "%#{content}%")}
		scope :filter_by_starts_with, -> (search) { where("name like :search or title like :search or content like :search", search: "%#{search}%")}
	  scope :filter_by_user, -> (user) { where user: user }
	  scope :filter_by_category, -> (category) { where category: category }
		validates :name, :presence => true
		validates :title, :presence => true,
											:length => { :minimum => 5 }
    mount_uploader :image, ImageUploader
    has_many :comments, :dependent => :destroy
		has_many :favorites, dependent: :destroy
			belongs_to :user
			belongs_to :category

end

app/models/subscriber.rb
class Subscriber < ApplicationRecord
  validates :email, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :favorites, dependent: :destroy
  has_many :favorited_posts, :through => :favorites, :source => :post
  has_many :followed_users, foreign_key: :follower_id, class_name: 'Follow'
  has_many :followees, through: :followed_users
  has_many :following_users, foreign_key: :followee_id, class_name: 'Follow'
  has_many :followers, through: :following_users
  has_many :comments, dependent: :destroy
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/cafes_controller.rb
class CafesController < ApplicationController
      before_action :authenticate_user!, except: [:index, :show]
      before_action :set_post, only: %i[ show edit update destroy ]

      # GET /posts or /posts.json
      def index
        @posts = Post.where(category_id: 2)
      end
        # if params.has_key?(:category)
        #   @category = Category.find_by_name(params[:category])
        #   @posts = Post.where(category: @category)
        # else
        #   @posts = Post.all
        # end


      # GET /posts/1 or /posts/1.json
      def show
      end

      # GET /posts/new
      def new
        @post = Post.new
      end

      # GET /posts/1/edit
      def edit
      end

      # POST /posts or /posts.json
      def create
        @post = Post.new(post_params.merge(user_id: current_user.id))

        respond_to do |format|
          if @post.save
            format.html { redirect_to @post, notice: "Post was successfully created." }
            format.json { render :show, status: :created, location: @post }
          else
            format.html { render :new, status: :unprocessable_entity }
            format.json { render json: @post.errors, status: :unprocessable_entity }
          end
        end
      end

      # PATCH/PUT /posts/1 or /posts/1.json
      def update
        respond_to do |format|
          if @post.update(post_params)
            format.html { redirect_to @post, notice: "Ура" }
            format.json { render :show, status: :ok, location: @post }
          else
            format.html { render :edit, status: :unprocessable_entity }
            format.json { render json: @post.errors, status: :unprocessable_entity }
          end
        end
      end

      # DELETE /posts/1 or /posts/1.json
      def destroy
        @post.destroy
        respond_to do |format|
          format.html { redirect_to posts_url, notice: "Увы" }
          format.json { head :no_content }
        end
      end

      private
      def filtering_params(params)
        params.slice(:user, :category, :starts_with)
      end
        # Use callbacks to share common setup or constraints between actions.
        def set_post
          @post = Post.find(params[:id])
        end

        # Only allow a list of trusted parameters through.
        def post_params
          params.require(:post).permit(:name, :title, :content, :image, :category_id)
        end

    end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    if params[:category_id]
      # @category = Category.find params[:category_id]
      @posts = Post.where("category_id = ?", params[:category_id])
      # @posts = @category.posts
    else
      @posts = Post.where(nil)
      filtering_params(params).each do |key, value|
      @posts = @posts.public_send("filter_by_#{key}", value) if value.present?
    end

  end
  @recpost = @posts.find_by(id: 1)
  @recpost2 = @posts.find_by(id: 2)
  @recpost3 = @posts.find_by(id: 9)
  @recpost4 = @posts.find_by(id: 4)
    # if params.has_key?(:category)
    #   @category = Category.find_by_name(params[:category])
    #   @posts = Post.where(category: @category)
    # else
    #   @posts = Post.all
    # end
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params.merge(user_id: current_user.id))

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: "Пост создан" }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: "Ура" }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Увы" }
      format.json { head :no_content }
    end
  end

  private
  def filtering_params(params)
    params.slice(:user, :category, :starts_with)
  end
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:name, :title, :content, :image, :category_id)
    end

end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cafes_helper.rb
module CafesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/promo_helper.rb
module PromoHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/subscribers_helper.rb
module SubscribersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


<div class="form__item">

  <div class="form__block">
    <%# <%= form.label :image %>
    <h4 class="form__block__title">Загрузите изображение</h4>
    <%= form.file_field :image, :class => "" %>
  </div>


  <div class="form__block">
    <%# <%= form.label :name %>
    <h4 class="form__block__title">Теги</h4>
    <%= form.text_field :name %>
  </div>

  <div class="form__block">
    <%# <%= form.label :title %>
    <h4 class="form__block__title">Заголовок</h4>
    <%= form.text_field :title %>
  </div>

  <div class="field">
      <h4 class="form__block__title">Категория</h4>
      <%= form.select :category_id, Category.pluck(:name, :id) %>
  </div>


  <div class="form__block">
    <%# <%= form.label :content %>
    <h4 class="form__block__title">Текст</h4>
    <%= form.cktext_area :content %>
  </div>

  </div>






  <div class="actions">
    <%= form.submit 'Обновить', class: "button_update_post" %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<%= stylesheet_link_tag "posts" %>

<div class="edit_post_container">

<h1>Редактирование поста</h1>


<%= render 'form', post: @post %>

<div class="edit_back_buttons">

<%= link_to 'Читать', @post %> 
<%= link_to 'Назад', posts_path %>
</div>
</div>

app/views/posts/index.html.erb
<%= stylesheet_link_tag "posts" %>
<p id="notice"><%= notice %></p>







<div class="mainpage_wrapper">
<%= react_component 'M_Banner' %>
<h2>Актуально сегодня | 06.02.2022</h2>
<%= react_component 'O_Posts_Cards_Topicals' %>
<h1>Попробуйте все блюда мира с Plato</h1>
<%= react_component 'M_Posts_Recommendations_Green', { post: @recpost } %>
<%= react_component 'M_Posts_Recommendations_Blue', { post: @recpost2 } %>
<h1>Что вы хотите найти?</h1>
<%= react_component 'M_Categories_Selection' %>
<%= react_component 'M_Posts_Recommendations_Orange', { post: @recpost3 } %>
<h1>Выберите интересующую вас кухню</h1>
<%= react_component 'O_Categories_Tags' %>
<div class="eastern">
<p>Восточная</p>
</div>
<div class="asian">
<p>Азиатская</p>
</div>
<div class="european">
<p>Европейская</p>
</div>
<div class="american">
<p>Американская</p>
</div>
<div class="northern">
<p>Северная</p>
</div>
<div class="african">
<p>Африканская</p>
</div>
<%= react_component 'M_Posts_Recommendations_Yellow', { post: @recpost4 } %>
</div>

app/views/posts/new.html.erb
<%= stylesheet_link_tag "posts" %>
<div class="post_create_container">

<h1>Создать пост</h1>

<%= render 'form', post: @post %>

<div class="edit_back_buttons">


<%= link_to 'Назад', posts_path %>
</div>
</div>

app/views/posts/show.html.erb
<%= stylesheet_link_tag "posts" %>
<p id="notice"><%= notice %></p>









     <%= react_component 'O_PostPart', { post: @post } %>


     <% if user_signed_in? %>
     <%= render "comments/form" %>
     <% else %>
     <div class="please">
     <p>Пожалуйста, <%= link_to 'войдите', new_user_session_path %> или <%= link_to 'зарегистрируйтесь', new_user_registration_path %> чтобы оставить комментарий.</p>
     </div>
    <% end %>
    <%= render @post.comments.select(&:persisted?) %>

<div class="recs">
    <h2>Заведения с похожей кухней:</h2>
    <div class="postrecsrow">
      <div class="postrec1"></div>
      <div class="postrec2"></div>
      <div class="postrec3"></div>
      <div class="postrec4"></div>
    </div>
</div>








  <div class="edit_back_buttons">

  <% if user_signed_in? && current_user.isadmin == true %>
  <%= link_to 'Изменить', edit_post_path(@post)  %>
  <% end %>
  </div>