config/routes.rb
Rails.application.routes.draw do
  resources :follows
  resources :categories do
    resources :posts
  end

  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users

  resources :users
  post 'users/:id/follow', to: "users#follow", as: "follow_user"
	post 'users/:id/unfollow', to: "users#unfollow", as: "unfollow_user"

  resources :subscribers
  get 'about/index'
  get 'promo/index'

  resources :posts do
    resources :comments
    resources :favorites
  end

  get 'users', to: 'users#index'
  get 'users/:id' => 'users#show'
  delete 'users/:id', to: 'users#destroy'

  get 'users/:id/following', :to => "users#following", :as => :following

  get 'posts/index'

  get 'promo', to: 'promo#index'
  get 'about', to: 'about#index'
  get 'restaurants', to: 'restaurants#index'
  get 'cafes', to: 'cafes#index'
  get 'bars', to: 'bars#index'
  get 'dishes', to: 'dishes#index'



  root 'posts#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/follow.rb
class Follow < ApplicationRecord
  belongs_to :follower, class_name: 'User'
  belongs_to :followee, class_name: 'User'
end

app/models/post.rb
class Post < ApplicationRecord
	  # scope :filter_by_starts_with, -> (content) { where("content like ?", "%#{content}%")}
		scope :filter_by_starts_with, -> (search) { where("name like :search or title like :search or content like :search", search: "%#{search}%")}
	  scope :filter_by_user, -> (user) { where user: user }
	  scope :filter_by_category, -> (category) { where category: category }
		validates :name, :presence => true
		validates :title, :presence => true,
											:length => { :minimum => 5 }
    mount_uploader :image, ImageUploader
    has_many :comments, :dependent => :destroy
		has_many :favorites, dependent: :destroy
			belongs_to :user
			belongs_to :category

end

app/models/subscriber.rb
class Subscriber < ApplicationRecord
  validates :email, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :favorites, dependent: :destroy
  has_many :favorited_posts, :through => :favorites, :source => :post
  has_many :followed_users, foreign_key: :follower_id, class_name: 'Follow'
  has_many :followees, through: :followed_users
  has_many :following_users, foreign_key: :followee_id, class_name: 'Follow'
  has_many :followers, through: :following_users
  has_many :comments, dependent: :destroy
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cafes_helper.rb
module CafesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/promo_helper.rb
module PromoHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/subscribers_helper.rb
module SubscribersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<link rel="stylesheet" href="stylesheets/style.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500;600;700&display=swap" rel="stylesheet">
<html>
  <head>
    <title>Plato</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag Ckeditor.cdn_url %>
</head>

  <body>

    <% if notice %>
  <p class="notice"><%= notice %></p>
  <% elsif alert %>
  <p class="alert"><%= alert %></p>
  <% end %>

  <%= react_component 'O_Topmenu'%>

  <% if user_signed_in? && current_user.isadmin == true %>
     <p><%= link_to 'Посты', posts_path %></p>
     <p><%= link_to 'Теги', categories_path %></p>
     <p><%= link_to 'Категории', categories_path %></p>
     <% if user_signed_in? && current_user.isadmin == true %>
     <p><%= link_to 'Люди', users_path %></p>
     <% end %>
   <% end %>

    <%= yield %>
<%= react_component 'O_Footer'%>



  </body>
</html>